apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      host: 'cassandra'
      port: 9042
      keyspace: 'logs'
      consistency: 'ONE'
      timeout: 30
      protocolVersion: 4
