apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-producer
  template:
    metadata:
      labels:
        app: log-producer
    spec:
      containers:
      - name: log-producer
        image: log-producer:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: log-producer
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: log-producer